In [1]:
import pandas as pd
import numpy as np

In [2]:
people = pd.read_csv('ted_merged.csv')

In [21]:
people = people.dropna()

In [22]:
# Data contains: link to wikipedia article, name of person, text of article.
people.head()

comments                                        description  duration  \
0      4553  Sir Ken Robinson makes an entertaining and pro...      1164   
1       265  With the same humor and humanity he exuded in ...       977   
2       124  New York Times columnist David Pogue takes aim...      1286   
3       200  In an emotionally charged talk, MacArthur-winn...      1116   
4       593  You've never seen data presented like this. Wi...      1190   

     event   film_date  languages   main_speaker  \
0  TED2006  1140825600         60   Ken Robinson   
1  TED2006  1140825600         43        Al Gore   
2  TED2006  1140739200         26    David Pogue   
3  TED2006  1140912000         35  Majora Carter   
4  TED2006  1140566400         48   Hans Rosling   

                                            name  num_speaker  published_date  \
0      Ken Robinson: Do schools kill creativity?            1      1151367060   
1           Al Gore: Averting the climate crisis            1      1151367060   
2                  David Pogue: Simplicity sells            1      1151367060   
3             Majora Carter: Greening the ghetto            1      1151367060   
4  Hans Rosling: The best stats you've ever seen            1      1151440680   

                                             ratings  \
0  [{'id': 7, 'name': 'Funny', 'count': 19645}, {...   
1  [{'id': 7, 'name': 'Funny', 'count': 544}, {'i...   
2  [{'id': 7, 'name': 'Funny', 'count': 964}, {'i...   
3  [{'id': 3, 'name': 'Courageous', 'count': 760}...   
4  [{'id': 9, 'name': 'Ingenious', 'count': 3202}...   

                                       related_talks  \
0  [{'id': 865, 'hero': 'https://pe.tedcdn.com/im...   
1  [{'id': 243, 'hero': 'https://pe.tedcdn.com/im...   
2  [{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...   
3  [{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...   
4  [{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...   

                     speaker_occupation  \
0                       Author/educator   
1                      Climate advocate   
2                  Technology columnist   
3    Activist for environmental justice   
4  Global health expert; data visionary   

                                                tags  \
0  ['children', 'creativity', 'culture', 'dance',...   
1  ['alternative energy', 'cars', 'climate change...   
2  ['computers', 'entertainment', 'interface desi...   
3  ['MacArthur grant', 'activism', 'business', 'c...   
4  ['Africa', 'Asia', 'Google', 'demo', 'economic...   

                             title  \
0      Do schools kill creativity?   
1      Averting the climate crisis   
2                 Simplicity sells   
3              Greening the ghetto   
4  The best stats you've ever seen   

                                                 url     views  \
0  https://www.ted.com/talks/ken_robinson_says_sc...  47227110   
1  https://www.ted.com/talks/al_gore_on_averting_...   3200520   
2  https://www.ted.com/talks/david_pogue_says_sim...   1636292   
3  https://www.ted.com/talks/majora_carter_s_tale...   1697550   
4  https://www.ted.com/talks/hans_rosling_shows_t...  12005869   

                                          transcript  
0  Good morning. How are you?(Laughter)It's been ...  
1  Thank you so much, Chris. And it's truly a gre...  
2  (Music: "The Sound of Silence," Simon & Garfun...  
3  If you're here today — and I'm very happy that...  
4  About 10 years ago, I took on the task to teac...

In [23]:
Ken = people[(people.main_speaker == 'Ken Robinson') & (people.event == 'TED2006')]



In [24]:
Ken

comments                                        description  duration  \
0      4553  Sir Ken Robinson makes an entertaining and pro...      1164   

     event   film_date  languages  main_speaker  \
0  TED2006  1140825600         60  Ken Robinson   

                                        name  num_speaker  published_date  \
0  Ken Robinson: Do schools kill creativity?            1      1151367060   

                                             ratings  \
0  [{'id': 7, 'name': 'Funny', 'count': 19645}, {...   

                                       related_talks speaker_occupation  \
0  [{'id': 865, 'hero': 'https://pe.tedcdn.com/im...    Author/educator   

                                                tags  \
0  ['children', 'creativity', 'culture', 'dance',...   

                         title  \
0  Do schools kill creativity?   

                                                 url     views  \
0  https://www.ted.com/talks/ken_robinson_says_sc...  47227110   

                                          transcript  
0  Good morning. How are you?(Laughter)It's been ...

In [25]:
Ken['transcript'].values

array([ 'Good morning. How are you?(Laughter)It\'s been great, hasn\'t it? I\'ve been blown away by the whole thing. In fact, I\'m leaving.(Laughter)There have been three themes running through the conference which are relevant to what I want to talk about. One is the extraordinary evidence of human creativity in all of the presentations that we\'ve had and in all of the people here. Just the variety of it and the range of it. The second is that it\'s put us in a place where we have no idea what\'s going to happen, in terms of the future. No idea how this may play out.I have an interest in education. Actually, what I find is everybody has an interest in education. Don\'t you? I find this very interesting. If you\'re at a dinner party, and you say you work in education — Actually, you\'re not often at dinner parties, frankly.(Laughter)If you work in education, you\'re not asked.(Laughter)And you\'re never asked back, curiously. That\'s strange to me. But if you are, and you say to someb

In [26]:
#Get the word counts for article
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
features = vectorizer.fit_transform(Ken['transcript'])

In [27]:
features

<1x822 sparse matrix of type '<class 'numpy.int64'>'
	with 822 stored elements in Compressed Sparse Row format>

In [28]:
vocab = vectorizer.get_feature_names()

In [29]:
vocab

['15',
 '16',
 '1930s',
 '19th',
 '20',
 '2065',
 '21',
 '30',
 '30s',
 '50',
 'ability',
 'about',
 'abstract',
 'academic',
 'academics',
 'according',
 'achievement',
 'actually',
 'adhd',
 'adopt',
 'adults',
 'advice',
 'affection',
 'afford',
 'afterward',
 'agents',
 'ago',
 'agreed',
 'al',
 'alien',
 'all',
 'allowed',
 'along',
 'always',
 'am',
 'america',
 'an',
 'and',
 'andrew',
 'angeles',
 'anniversary',
 'annoyed',
 'annoying',
 'another',
 'anything',
 'anyway',
 'applause',
 'are',
 'aren',
 'around',
 'art',
 'artist',
 'artists',
 'arts',
 'as',
 'ask',
 'asked',
 'at',
 'attention',
 'auditioned',
 'available',
 'avert',
 'avon',
 'aware',
 'away',
 'ba',
 'back',
 'ballet',
 'based',
 'be',
 'bearing',
 'beat',
 'became',
 'because',
 'become',
 'bed',
 'been',
 'before',
 'beginning',
 'being',
 'beings',
 'believe',
 'beneath',
 'benign',
 'benignly',
 'better',
 'big',
 'bit',
 'blood',
 'blown',
 'board',
 'bodies',
 'body',
 'book',
 'born',
 'bottom',
 'box

In [30]:
dist = np.sum(features.toarray(), axis=0)
dist

array([  1,   2,   1,   1,   1,   1,   1,   1,   1,   2,   2,  20,   1,
         3,   1,   1,   1,   6,   2,   1,   1,   1,   1,   1,   1,   1,
         1,   1,   1,   1,  22,   1,   1,   1,   2,   1,   9, 103,   1,
         3,   1,   1,   1,   2,   2,   3,   4,  19,   2,   3,   2,   2,
         1,   2,  12,   1,   2,  21,   1,   1,   1,   1,   1,   1,   2,
         1,   3,   5,   1,  19,   1,   1,   1,  12,   1,   2,   6,   1,
         1,  10,   1,   2,   1,   1,   1,   1,   3,   1,   1,   1,   1,
         1,   2,   1,   3,   1,   1,   4,   1,   3,   1,   1,   2,   1,
        19,  13,   3,   1,   1,   2,   9,   4,   2,   1,   1,   1,   1,
         1,   1,   1,   1,   1,   1,   1,   1,   1,   8,   1,   1,   1,
         1,   7,   3,   1,   1,   1,   1,   1,   1,   2,   2,   1,   2,
         1,   1,   1,   1,   2,   1,   3,   1,   2,   2,   1,   1,   4,
         5,   2,   1,   1,   6,   2,   1,   1,   1,   1,   1,   1,   1,
         1,   2,   1,   1,   1,   1,  11,   6,   1,   2,   1,   

In [31]:
#Sort the word counts for the article
#Turning dictonary of word counts into a dataframe

Ken_word_count_table = pd.DataFrame({'token':vocab, 'count':dist}).sort_values('count')

In [32]:
Ken_word_count_table.sort_values('count', ascending=False).head(15)

count     token
697    153       the
37     103       and
719     80        to
819     79       you
479     75        of
775     63        we
342     56        in
359     52        it
696     46      that
357     45        is
705     44      they
768     41       was
618     41       she
379     39  laughter
711     30      this

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()

In [34]:

dtm = vect.fit_transform(people['transcript'])

In [35]:
dtm.shape

(2461, 58772)

In [36]:
features = vect.get_feature_names()

In [37]:
features

['00',
 '000',
 '0000',
 '000000004',
 '0000001',
 '000001',
 '00001',
 '000042',
 '0001',
 '0009',
 '000th',
 '001',
 '0015',
 '003',
 '004',
 '004867',
 '005',
 '005545',
 '005634',
 '005961',
 '006',
 '007',
 '007080',
 '008106',
 '008309',
 '008494',
 '01',
 '0111',
 '02',
 '020',
 '024',
 '025',
 '03',
 '034',
 '035',
 '04',
 '040',
 '0400',
 '041',
 '047',
 '048',
 '05',
 '050',
 '05049',
 '051',
 '052',
 '06',
 '064',
 '07',
 '077',
 '08',
 '080',
 '09',
 '098',
 '0b2472',
 '0s',
 '10',
 '100',
 '1000',
 '1000awesomethings',
 '1000th',
 '100th',
 '100ths',
 '101',
 '10165',
 '102',
 '103',
 '103rd',
 '104',
 '105',
 '106',
 '107',
 '107th',
 '108',
 '109',
 '109th',
 '10am',
 '10b',
 '10s',
 '10th',
 '10x',
 '10x10',
 '10x8',
 '11',
 '110',
 '111',
 '112',
 '113',
 '114',
 '115',
 '117',
 '118',
 '119',
 '11pm',
 '11th',
 '12',
 '120',
 '1200',
 '120th',
 '121',
 '1214b',
 '122',
 '1229',
 '123',
 '12345678',
 '124',
 '124th',
 '125',
 '1252',
 '1258',
 '125th',
 '126',
 '127',


In [38]:
#Examine the TF-IDF for the article
#Remember that the  article is at index 35817
Ken

comments                                        description  duration  \
0      4553  Sir Ken Robinson makes an entertaining and pro...      1164   

     event   film_date  languages  main_speaker  \
0  TED2006  1140825600         60  Ken Robinson   

                                        name  num_speaker  published_date  \
0  Ken Robinson: Do schools kill creativity?            1      1151367060   

                                             ratings  \
0  [{'id': 7, 'name': 'Funny', 'count': 19645}, {...   

                                       related_talks speaker_occupation  \
0  [{'id': 865, 'hero': 'https://pe.tedcdn.com/im...    Author/educator   

                                                tags  \
0  ['children', 'creativity', 'culture', 'dance',...   

                         title  \
0  Do schools kill creativity?   

                                                 url     views  \
0  https://www.ted.com/talks/ken_robinson_says_sc...  47227110   

                                          transcript  
0  Good morning. How are you?(Laughter)It's been ...

In [39]:
#So we'll examine the document term matrix at index 35817 and pull out the TF-IDF by each word.
#First we'll make a dictionary
word_scores = {}
for word in vocab:
    word_scores[word] = dtm[0, features.index(word)]

In [41]:
Ken_word_scores = pd.DataFrame(list(word_scores.items()),
                      columns=['word', 'tfidf'])

In [42]:
Ken_word_scores.sort_values('tfidf', ascending=False).head(15)

word     tfidf
599        the  0.423228
689        and  0.285034
3           to  0.221475
416        you  0.219063
17          of  0.207802
595        she  0.201319
344         we  0.177413
736  education  0.163749
631         in  0.155537
522         it  0.144310
83     gillian  0.143141
765   laughter  0.140499
513       that  0.127815
683       they  0.126092
456         is  0.124985

In [50]:
#Is Obama closer to Clinton than to Beckham?
#Note that we're computing the cosine similarity (which ranges from 0 to 1, where 1 is most similar) not the cosine distance which we can use as well.
#cosine_distance = (1-cosine_similarity)
#We should find that the article about president Obama is closer to the one about former president Clinton than that of footballer David Beckham.


from sklearn.metrics.pairwise import cosine_similarity
clinton= people[people['main_speaker'] == 'Al Gore']
beckham = people[people['main_speaker'] == 'Hans Rosling']

In [51]:
cosine_similarity(dtm[Ken.index], dtm[clinton.index])

array([[ 0.64813347,  0.61466903,  0.66891491,  0.4935201 ]])

In [52]:
cosine_similarity(dtm[Ken.index], dtm[beckham.index])

array([[ 0.64535197,  0.57008011,  0.41286117,  0.52590646,  0.71497667,
         0.61061769,  0.63986318,  0.45639159,  0.60218465]])

In [53]:
#cosine distance
from sklearn.metrics.pairwise import pairwise_distances
pairwise_distances(dtm[Ken.index], dtm[clinton.index], metric='cosine')

array([[ 0.35186653,  0.38533097,  0.33108509,  0.5064799 ]])

In [55]:
pairwise_distances(dtm[Ken.index], dtm[beckham.index], metric='cosine')

array([[ 0.35464803,  0.42991989,  0.58713883,  0.47409354,  0.28502333,
         0.38938231,  0.36013682,  0.54360841,  0.39781535]])

In [56]:
#Build a nearest neighbor model for document retrieval¶
dtm.shape

(2461, 58772)

In [57]:
from sklearn.neighbors import NearestNeighbors
neighbors = NearestNeighbors(n_neighbors=10)

In [58]:
neighbors.fit(dtm)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=1, n_neighbors=10, p=2, radius=1.0)

In [59]:
#Who is closest to Obama?
distances, indices = neighbors.kneighbors(dtm[Ken.index], return_distance=True)

In [60]:
distances

array([[ 0.        ,  0.74578179,  0.74622474,  0.74650649,  0.74824386,
         0.75480226,  0.75501434,  0.75747279,  0.7589473 ,  0.76040965]])

In [61]:
indices

array([[   0,  364,  663, 1418,  197, 1100,  558,  354,   65, 1827]])

In [62]:
test = zip(people.iloc[indices[0]]['main_speaker'], distances[0])

In [63]:
print(list(test))

[('Ken Robinson', 0.0), ('David Carson', 0.74578179165826863), ('Ken Robinson', 0.74622474033312169), ('Ken Robinson', 0.74650649450949647), ('Nicholas Negroponte', 0.74824385773585855), ('Bryan Stevenson', 0.75480225766005293), ('Marc Pachter', 0.75501434070314621), ('Kary Mullis', 0.75747278795628181), ('Jane Goodall', 0.75894730044105208), ('Ricardo Semler', 0.76040964943669642)]
